config/routes.rb
Rails.application.routes.draw do
  # Taskリスト用のルートを設定する
  resources :todos
  root "todos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# 処理の流れ
# set_taskを実行し，idに従ってshow,edit,update,destroyから適切なタスクを見つけ，@taskにセットする
# 

class TodosController < ApplicationController
    # フィルタに該当するメソッドの実行前にこのアクションを実行するよ〜と定義
    before_action :set_todo, only: [:show, :edit, :update, :destroy]

    def index
        @todos = Todo.all
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        if @todo.save
            redirect_to @todo, notice: 'Todo was successfully created.'
        else
            render :new
        end
    end

    def update
        @todo = Todo.find(params[:id])
        if @todo.update(todo_params)
            redirect_to @todo, notice: 'Todo was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @todo.destroy
        redirect_to tasks_url, notice: 'Todo was successfully destroyed.'
    end

    private
    # params[:id]に基づいて特定のTaskレコードがデータベースから取得され，インスタンス変数@taskにセットされる．
    def set_todo
        @todo = Todo.find(params[:id])
    end
    # フォームから送信されたパラメータを受け取る
    # params.require(:task)で:taskキーが含まれていることを確認する
    # permit(:titlem :completed)で:taskパラメータ内の:titleと:completedのみを許可する
    # 許可されたパラメータを返す
    def todo_params
        params.require(:todo).permit(:title, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<!-- app/view/tasks/_form.html.erb -->
<%= form_with(model: todo, local: true) do |form| %>
    <% if todo.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
            <ul>
                <% todo.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <%end%>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div class="field">
        <%= form.label :completed %>
        <%= form.check_box :completed %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>

<% end %>

app/views/todos/edit.html.erb
<!-- app/views/tasks/edit.html.erb -->
<h1>Edit Todo</h1>
<%= render 'form', todo: @todo %>
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<!--app/view/tasks/index.html.erb-->
<h1>Todo List</h1>
<%= link_to 'New Todo', new_todo_path %>
<ul>
    <% @todos.each do |todo| %>
        <li>
            <%= link_to todo.title, todo %>
            <%= link_to 'Edit', edit_todo_path(todo)%>
            <%=link_to 'Destroy', todo, method: :delete, data:{confirm: 'Are you sure?'}%>
        </li>
    <%end%>
<ul>

app/views/todos/new.html.erb
<!--app/views/tasks/new.html/erb-->
<h1>New Todo</h1>
<%= render 'form', todo: @todo %>
<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<!-- app/views/tasks/show.html.erb-->
<h1><%= @todo.title %></h1>
<p> <%= @todo.completed ? "Completed" : "Not Completed"%></p>
<%= link_to 'Edit', edit_todo_path(@todo)%>
<%= link_to 'Back', todos_path%>